nowo_device_intelligence:
    enabled: true
    observe_on_every_request: true
    endpoint:
        response:
            device_id: true
            confidence: true
            risk: true
    doctrine:
        enabled: true
        table_prefix: device_intelligence_
    profiles:
        default:
            rate_limit:
                policies:
                    collect:
                        limit: 60
                        interval: '1 minute'
                    coupon:
                        limit: 3
                        interval: '24 hours'
